using System;
using System.Text;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;

namespace LoisLane {

    internal static class Echo {

        internal static Byte LOG_LEVEL = 10;

		internal static void WelcomeText() {
			Out("\n\nLois Lane\n" +
			 @"
............................................................
...........................+I?8DD?..........................
.........................=:$8DDDDD8O........................
.......................7$8II7ODDDDOOO?......................
......................ZONNDO=8DNNDDNDZD.....................
......................DDNNDDZDZ8DDD8D8OZ....................
.....................DDNNNNNDDDDDZ=~8D8D....................
.....................DDNN88I+=:::::~DD?ZI...................
.....................NDD=~8ZI8:=::~=+DDNO...................
.....................DD$~~:+7?=:O8O$?DDD8...................
.....................DZI=:,,,::?I?~8DDDD8...................
.....................D??+~::~~:+~~:?8DDDD...................
.,...................7DI==::=NI?~~+8DDDDD...................
.....................+D7=~?=O:+==+7DDDDDD...................
......................I+?=~~$+Z+?7DZDDDDD...................
.,...................=?=??~~~~=?DDDDDDDDD,..................
....................~...=ZD7?+DNDDDDDDDDDO..................
..................,::+... $DDDDDD7DDDDDDDD..................
.................,~:::?.. .D+?+.....DDDDDDD.................
..............ND?:=::::7 .D?I++...=DDDDDDDDDD=..............
..........$=::ZDD::::::I,$..?+7I,7DDDDDDDDDDO8D,............
.......=:?:::::ZI:::?7$::I,..?+++,7DDDDDD88DDD87............
.......::::$:::?=::::Z:::Z~..8==+I.8DDDOZ88DD88.............
......=:::::?~:+8::::+::::=::.~.7=.8OO7DO8DDDD=.............
......$::::::=~:8=::::?::::.,:..=O..DDDDZ8DDZ?=,............
......+:::::::7~D7:::::::::7.+.:..?.DDDDDDOO?7~+............
......=:=~::::++D+:::::~:::~..I..:?,DDDD8D7I~~~~=...........
......Z~==~:=:~?D~::::::::::+..7..,DDDD+~7?+~~~~~7..........
......+:::::~:=~O::::::::::::.,.7..D8:~~~~~Z~~~~=?Z.........
......::::::::?:O=::::~::Z:::I...$,~Z.~::~~~?~~~~~~+........
......=:::::::$:8~~~~:~:::::::...=.,$.$:::~~+~~~~~~~~.......
.....+::::::::+:$~~~~~~=::$:::....7.$.$:::::?I~~:~~:~:......
.....I:::::::?D=7~~~~~I::::$::,..,Z.$.+:::::?+:~:::~==~?....
.....::::::::N:?Z=~~~~~~~~:+::7...+.$.?:::~7,OI::I~=::=7?...
....+:::::::=N,~O==~:~~~~~~~D~$.+,,II?~:::~I,,$~=:7~?~~~~7..
....I::::::+ZD.~D=Z~~~~~~~~~?~7.,,~?~,?~~~:,,,,OI7?+=~::::..
....:::::$::DN.Z~~~~~~~~~~===D~~,~~ZII$I=~:.,,,,Z~:::?::::..
...O::::Z:~+DD.Z,~~~~~~~====I$=,$I~O=++Z~~Z,,,,,=~~:::::=7..
...::::7::+$D7.+.+~~~~~===~:~=,,$=?+=IZ:~::.,,,,~::::::~=+..
..Z:::+:=~::D~.+.O~~=====~~~==.~III~7Z7=::,..,,,:~~::~:~I...
..::::=~:=:,D,=7.D===~:~~~~~~$::.?$7I7I+=:..,,,=I::::::~=...
.O7Z:=+~~7,.D.NO,~I+~~~~:::~:D~?ZII7=7$:::,....?~::~=~:=I...
.:~++~~:~7:I7ZZ.N:==~:~::::+:N~O:$=Z$Z$:?++....D::::::::....
.=:::::?+~.?7~?,~::::I+~::::OD~D:D8O=DO=I$+~..+::::::::~....
O:::::~=~~.O8I$D?::::::~+::~D~~~$$$II?~=+?=+Z,:::::::::+....
:::::=?==O7I?OZN~:::::::+~:~D=~=====I=:=~=D8~?O::::~~::.....            
            ", 9);
		}

		internal static void HelpText() {
			Out(@"
                Lois Lane

                Creates document reports for mere mortals who are clearly far too lame to use CLI reports.

                LoisLane.exe -design-document -file ""c:\\path\\to\\input.json"" -out-file ""c:\\path\\to\\new.docx""
                
                LoisLane.exe -design-document -json {""submitterName"":""james bond""} -out-file ""c:\\path\\to\\new.docx""

            ", 1);
		}

		internal static void ErrorReport(string[] badInput) {
			var errReport = new StringBuilder();
			foreach (var misunderstoodWord in badInput)
				errReport.AppendLine("No switch available for: " + misunderstoodWord);
			
			Out(errReport, 1);
		}

        public static void Out(string message, int noisiness = 1) {
            
            if(noisiness <= LOG_LEVEL) {
                Console.WriteLine(message);
            }
        }

        public static void Out(StringBuilder sb, int noisiness = 1) {
            
            if(noisiness <= LOG_LEVEL) {
                Console.WriteLine(sb);
            }
        }

    }
}
